plugins {
    id 'java'
    id 'net.fabricmc.fabric-loom' version '1.15' apply false
    id 'net.fabricmc.fabric-loom-remap' version '1.15' apply false
}

allprojects {
    group = 'io.github.configstackmc'
    version = '1.0.0'
}

def targetJavaVersion = (findProperty('javaVersion') ?: '25') as int

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(targetJavaVersion)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = targetJavaVersion
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}
