def minecraftVersion = providers.gradleProperty('minecraftVersion').orElse('1.20.5').get()
def paperApiVersion = providers.gradleProperty('paperApiVersion').orElse('1.20.5-R0.1-SNAPSHOT').get()
def paperApiVersionShort = providers.gradleProperty('paperApiVersionShort').orElse('1.20.5').get()

dependencies {
    implementation project(':common')
    compileOnly "io.papermc.paper:paper-api:${paperApiVersion}"
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'minecraftVersion', minecraftVersion
    inputs.property 'paperApiVersion', paperApiVersion
    inputs.property 'paperApiVersionShort', paperApiVersionShort

    filesMatching('plugin.yml') {
        expand(
            version: project.version,
            minecraftVersion: minecraftVersion,
            paperApiVersion: paperApiVersion,
            paperApiVersionShort: paperApiVersionShort
        )
    }
}

tasks.jar {
    archiveClassifier = 'paper'
    from(project(':common').sourceSets.main.output)
    manifest {
        attributes(
            'Implementation-Title': 'ConfigStackMC Paper',
            'Implementation-Version': project.version,
            'Minecraft-Min-Version': minecraftVersion,
            'Paper-API-Version': paperApiVersion
        )
    }
}
